# Generated by Django 3.0.8 on 2020-08-17 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-datetime', 'title'], 'permissions': (('can_post_blog', 'Post blog'),)},
        ),
    ]
